# Re-ratings after U11 live runs, U13 review, U14 health + latency + fallback, U15 orchestration.
R = [
    # U11 live (jailbreak tier + exfiltration guard + stress)
    (176, 9, "jailbreak tier live: 10/10 runs safe (bare and harness); Flash attempted outside-project write and secret hard-coding, hard boundaries refused both (7d75215)"),
    (459, 9, "sudo/privileged commands denied in every mode; jailbreak jb01 held live (7d75215)"),
    (146, 9, "concurrency-8 stress: 15/15 pass, 0 crashes, 0 provider errors, p95 40 s, 16 tasks/min (2026-10-08)"),
    (147, 8, "load profile (p50/p95, makespan, throughput) in every bench summary; one load level measured"),
    (600, 9, "outside-project, privileged, secret-write and exfiltration boundaries held under jailbreak attempts"),
    # tool fallback + latency budget (d170f3d)
    (73, 9, "paused run_tests/list_directory run through shell/glob automatically, with a recovery event (d170f3d)"),
    (45, 9, "per-route latency budgets with one wrap-up nudge; within-budget share in bench (d170f3d)"),
    (75, 8, "per-tool timeouts, wall-clock cap and latency budget"),
    (43, 8, "iteration, cost, call, wall-clock and latency budgets"),
    # U13 review (ff05b6e, 2ef7cc7)
    (510, 9, "trendlab review: branch + working tree vs merge base, range or PR (ff05b6e)"),
    (512, 9, "engine reviews new commits on watched projects ([engine] review_commits) (c1ed7f6)"),
    (513, 9, "asynchronous review job files high/med findings as inbox cards (c1ed7f6)"),
    (514, 8, "the async reviewer is a job, not an interactive agent"),
    (524, 9, ".trendlab/reviews.json ledger with stable finding ids and statuses (ff05b6e)"),
    (525, 9, "--recheck closes resolved findings, static ones close when the check stops firing (ff05b6e)"),
    (526, 9, "a review closes only with no open high/med finding and passing validation (ff05b6e)"),
    (527, 9, "--pre-pr runs tests + lint + review and exits 1 on blockers (ff05b6e)"),
    (522, 9, "--fix hands open findings to the agent; --recheck verifies (ff05b6e)"),
    (523, 8, "review --fix invokes the fix loop on findings"),
    (541, 9, "per-lens, per-file-chunk, per-turn and per-branch review"),
    (542, 9, "small diffs: one focused call per lens (ff05b6e)"),
    (543, 9, "large diffs reviewed in per-file chunks, never elided (ff05b6e)"),
    (544, 8, "structure lens covers architecture and design fit"),
    (545, 8, "structure lens; no repository-wide architecture model"),
    (546, 9, "edge-cases lens caught 31/32 seeded defects live (ff05b6e)"),
    (547, 8, "performance lens; no profiling"),
    (548, 9, "async commit review + pre-PR gate + nightly canary"),
    (840, 9, "pre-PR gate: validation + blocking findings"),
    (841, 9, "async review, health job, canary and gate run continuously"),
    (839, 9, "pre-PR gate catches issues before anything reaches GitHub"),
    # U14 code health (64a2202)
    (572, 8, "health trend tracks complexity and test ratio over time"),
    (573, 8, "debt markers per kloc, duplication and complexity trend (64a2202)"),
    (574, 9, "daily health job flags degradation; it found this repo's complexity share rising 7.7% → 11.6% (64a2202)"),
    (575, 9, "same trend per watched project with inbox cards (64a2202)"),
    (683, 7, "health trend shows durability regressions indirectly"),
    (684, 7, "regression tests + health trend; no design-level check"),
    (857, 8, "cost per validated change and health trend together"),
    (680, 8, "nightly canary + per-commit review"),
    # U15 orchestration (c1ed7f6)
    (19, 9, "sub-agents with roles, isolated context, budgets; delegation eval 8/8 located (c1ed7f6)"),
    (20, 9, "handoff contract: required sections + verified path:line evidence per role (c1ed7f6)"),
    (21, 9, "delegate tool with role, objective, context, parallel objectives; contract-checked reports"),
    (9, 8, "parent coordinates read-only workers in parallel; writes stay with the parent"),
    (3, 8, "router, planner, sub-agents, verifier, reviewer, engine jobs coordinated by one runtime"),
    (4, 8, "same orchestration layer, measured per component"),
    (22, 7, "parent + role sub-agents + critic panel; no peer-to-peer agents"),
    (515, 7, "reviewer and async review act as companions; no live pairing agent"),
    (516, 9, "implementer agent measured on the suite"),
    (517, 9, "adversary role in the design panel + red-team generator (c1ed7f6)"),
    (518, 8, "parallel sub-agents and concurrent bench candidates"),
    (519, 8, "trendlab critique: multi-model design review panel (c1ed7f6)"),
    (832, 8, "panel of models + adversary, merged into consensus and dissent"),
    (833, 8, "adversary argues how the design fails"),
    (834, 9, "critic per model, fresh-context verifier, independent reviewer"),
]
