# Re-ratings after U28 (self-correction, few-shot router, prompt registry, chat import, step
# checkpoints), U29 (tail, index cache), U30 (co-design, memory eval, probes, failover).
R = [
    (13, 9, "self-correction measured: 350 stored runs saw a failing check, 98.9% ended passing (b5be948)"),
    (534, 9, "same measurement of turn-by-turn bug elimination"),
    (511, 9, "tests after edits, step validations, verifier; edit→validation latency per row"),
    (505, 9, "step validation checkpoints + per-step file checkpoints (a015340)"),
    (520, 9, "a checkpoint per plan step; undo back to before any step (a015340)"),
    (521, 9, "same, plus the run-level checkpoint and cassettes"),
    (533, 8, "review gate and verifier sit inside execution"),
    (420, 8, "few-shot examples in the router prompt, measured (b5be948)"),
    (421, 8, "few-shot router: 97.5% → 100% held-out, Brier 0.023 → 0.010 (b5be948)"),
    (422, 8, "zero-shot baseline measured against few-shot on the same held-out set"),
    (91, 9, "17 harness prompts registered with hash, size and the eval measuring each; lock file + test (b5be948)"),
    (617, 9, "prompt registry pins every structural prompt; changes need their eval re-run"),
    (618, 8, "drivers per model + communication rules + registry"),
    (619, 8, "prompt changes are visible (lock) and measured"),
    (92, 9, "system prompt layers hashed per call (prompt drift) and registered prompts locked"),
    (695, 9, "Claude Code and any OpenAI-style chat log import into one store (f7b5a80)"),
    (696, 9, "same: search, stats, trace, rca and failures span imported harnesses"),
    (714, 9, "chat-log and Claude Code formats normalised to one event schema (f7b5a80)"),
    (716, 9, "one session schema for native and imported sessions"),
    (717, 9, "same"),
    (715, 8, "documented JSONL events, OTel export, cassette format"),
    (820, 8, "review, arch, mutate, spec, health, pr, tail work on any repo regardless of harness"),
    (821, 8, "same tools + importers for other harnesses' logs"),
    (823, 8, "imports from other harnesses; standalone tools"),
    (701, 9, "`trendlab tail` follows any run's events live, including other terminals and engine jobs (9583315)"),
    (702, 9, "same"),
    (813, 9, "code index cached by size and mtime: 1.33 s → 0.17 s warm on 827 files (c5749b9)"),
    (798, 8, "index, vector and session caches on disk"),
    (815, 8, "warm index 7.8x faster; quick review 6x fewer calls"),
    (835, 8, "plan co-design: a rejection with a reason becomes a revised plan, re-approved (ab32098)"),
    (831, 8, "person sets intent and approves; agent revises on their words"),
    (606, 9, "plan gate, co-design, approvals and merge stay with the person"),
    (29, 9, "memory eval: 8/8 durable facts kept, 0/4 run narration leaked (bdbc26a)"),
    (90, 9, "learned memory injected into the system prompt; learning precision measured"),
    (173, 8, "contamination probe: Flash reproduced 0/10 hidden tests, mean similarity 0.44 (bd2f211)"),
    (170, 9, "reference-bias probe: verifier passed reference and equivalent fixes 18/18 each, gap 0 (bd2f211)"),
    (801, 8, "failover to a configured local model tested; Ollama on the machine"),
    (72, 9, "model fallback chains; failover to local tested (d900b93)"),
    (803, 9, "cloud outage → local model failover + cooldown retries"),
    (868, 8, "docs/OPERATING_MODEL.md: each lifecycle stage with its command and measured number (b199d9e)"),
    (859, 8, "same operating model"),
    (865, 8, "intake → plan → implement → verify → review → trace → ship → observe → learn → monitor → improve"),
    (862, 7, "systems-level checks (arch, health, budgets) inside the agent workflow"),
    (814, 8, "triage, review, health, tail, cost automate routine checks"),
    (816, 8, "`trendlab review` beside any editor"),
    (817, 8, "standalone read-only tools; nothing pushed or merged"),
    (818, 8, "tail, review, health run alongside any session"),
    (819, 8, "parallel sub-agents, worktrees, concurrent bench"),
    (824, 8, "adds review, mutation, spec, arch, PR triage to any stack"),
]
