# Re-rating pass of terms rated before the programme, where the programme's measured work now
# supports a higher rating. Terms without new evidence are left alone (2026-10-08).
R = [
    (1, 9, "every subsystem measured: 86-task suite, 12 eval modes, canary, replay corpus, ledger of evidence"),
    (2, 9, "runtime with invariants, coded failures, cooldown recovery; 10/10 under 20% injected faults"),
    (5, 9, "control loop with evaluator, scope, communication and latency checks, each tested"),
    (6, 9, "agent loop replays identically from cassettes on 8/8 real sessions (5e76e9d)"),
    (7, 9, "same execution loop, measured under chaos and replay"),
    (10, 9, "reason-act loop with tool rescue for text tool calls; measured on the suite"),
    (26, 9, "agent state machine with invariant checks after every transition (777f673)"),
    (27, 9, "conversation state persisted, compacted with 100% fact retention (0dc8673)"),
    (36, 9, "capability boundaries held under 10/10 jailbreak attempts (7d75215)"),
    (37, 9, "sub-agents read-only, privileged denied, credential files refused, secrets taint network"),
    (41, 9, "ask / auto-edit / auto / unsafe modes plus plan gate and remote approvals"),
    (46, 9, "per-run cost cap + monthly/project budgets with alerts (3614a6b)"),
    (51, 9, "tool layer: tiered output, health breaker, automatic fallback, postconditions, symbol check"),
    (54, 9, "native tools + structured fallback + text-call rescue; JSON mode with repair"),
    (58, 9, "tool and output schemas validated, invalid output repaired once"),
    (65, 9, "every failure path classified into the taxonomy; crashes measured in bench"),
    (67, 9, "BM25 when embeddings are down, 100% fallback compaction, tool fallback, cooldown retries"),
    (69, 9, "gateway retries + run-level cooldown; chaos canary 18 faults, 10/10 (1dffa3f)"),
    (70, 9, "exponential backoff with jitter + cooldown"),
    (71, 9, "fallbacks for models, tools, retrieval and compaction, each tested"),
    (78, 9, "OpenAI-compatible, Anthropic and Ollama adapters with JSON mode and per-role sampling"),
    (82, 9, "permission engine + injection taint + secret taint + change scope (7d75215, 8c331e8)"),
    (83, 9, "guardrails measured: adversarial 5/5, jailbreak 10/10, red-team 15/15"),
    (94, 9, "span tree + cassette of every model and command response"),
    (97, 9, "typed JSONL events with span ids, rotation, OTel export"),
    (99, 9, "tokens and cost per call, role, model and project, fully loaded (3614a6b)"),
    (101, 9, "bench harness: suite, compare, gate, canary, ablations, and 8 component evals"),
    (104, 9, "86 tasks in 7 tiers, holdout, version fingerprint incl. grading rules"),
    (105, 9, "every task has a hidden test, reference and forbid checks; --verify-suite"),
    (106, 9, "fixtures and generated suite repos materialised per run"),
    (139, 9, "suite version fingerprints tasks and grading rules; canary history across versions"),
    (185, 9, "online quality, async commit review, daily health and budget checks on real work"),
    (501, 9, "engine: watch, canary, health, review, budget, meta-loop cards with remedies"),
    (502, 9, "verifier per surfaced turn + per-turn commits for review (8c331e8)"),
    (503, 9, "local verification: tests, verifier, review gate, symbol check — all local"),
    (535, 9, "step validation after each plan step; postconditions after each edit"),
    (591, 9, "replay regression suite detects behaviour change at $0 (5e76e9d)"),
    (592, 9, "chaos, determinism and replay measurements"),
    (593, 9, "replay regression + canary catch a fix that breaks another path"),
    (594, 9, "canary history, failure taxonomy trends and replay"),
    (601, 9, "destructive requests recoverable via checkpoints; ad05/jb04 held live"),
    (602, 9, "the harness never merges"),
    (613, 9, "agent boundaries held under jailbreak and injection tiers"),
    (614, 9, "autonomy modes + plan gate + change scope"),
    (615, 9, "operational guardrails measured live"),
    (625, 9, "merging is never automated; push and merge stay with the owner"),
    (626, 9, "privileged denied, destructive asks, exfiltration gated, change scope enforced"),
    (636, 9, "plan gate, remote approvals, unattended deny-by-default"),
    (638, 9, "every run: coded outcome, cost, diff, turn commit, cassette"),
    (639, 9, "[governance] scope, communication, change scope, turn commits; [economics] budgets"),
    (640, 9, "policies drive execution: route settings, permission policy, sampling policy"),
    (691, 9, "sessions observable via trace tree, rca, stats, dashboard, replay"),
    (692, 9, "session trace = span tree + events + cassette"),
    (693, 9, "SQLite session store with search (exact, ranked, semantic), stats, export"),
    (711, 9, "structured events per session with retention"),
    (748, 9, "spend per period and change vs the previous period (3614a6b)"),
    (750, 9, "tokens and cost attributed per role, model and project"),
    (751, 9, "cost per run and per validated change"),
    (752, 9, "cost per model call recorded"),
    (758, 9, "fully loaded accounting incl. engine jobs and reviews (ff05b6e)"),
    (763, 9, "router sets the route's models; Flash planner/critic/reviewer measured equal to Pro"),
    (770, 9, "budgets, latency budgets and cost caps enforced"),
    (780, 9, "measured savings: quick review 6x fewer calls, Flash planner 3.5x cheaper at equal quality"),
    (781, 9, "heavy roles gated by route; costs ratio in the release gate"),
    (782, 9, "cheapest viable model chosen by measurement (planner, reviewer, critic)"),
    (794, 9, "trendlab cost and stats show where every dollar went"),
    (838, 9, "taxonomy, ledger, turn commits, cassettes, review ledger"),
    (827, 9, "nightly canary, daily health, async review, budget alerts"),
    (828, 8, "continuous checks; vigilance still needs the owner to read the cards"),
    (836, 8, "review ledger with recheck supports human co-review"),
    (837, 8, "turn commits and review ledger tie every change to a run"),
    (851, 8, "router + scope budget + change scope before initiative"),
    (858, 9, "evidence ledger: no rating moves without a commit or a number"),
    (860, 8, "harness designed around measured agent failure modes"),
    (861, 8, "worktrees, turn commits, review gate fit the agent into git workflow"),
    (866, 8, "CLI + engine + bench + review + PR tooling"),
    (867, 9, "verify, review, health, canary, replay and gates form one quality system"),
]
