# Re-ratings after U23 agent behaviour, U24 architecture/parsimony, U25 mutation testing,
# U26 runtime controls, U27 security inventory (2026-10-08).
R = [
    # U23 agent behaviour (ccae579)
    (604, 9, "skip/xfail added, assertions removed, test files deleted or CI loosened are flagged; 0 false alarms on 80 commits (ccae579)"),
    (584, 8, "sycophancy tier: confident wrong diagnoses; Flash followed 0/10 and fixed the real cause 10/10 (ccae579)"),
    (595, 8, "constitution rules each enforced, tested and measured; misalignment shows as rule violations"),
    (597, 8, "overreach rate: edits on question tasks, per bench summary (ccae579)"),
    (598, 8, "timidity rate: no change or a question on a clear fix (ccae579)"),
    (643, 8, "both rates measured; route settings tune how proactive each request kind is"),
    (558, 8, "overreach rate + scope budget + change scope"),
    (609, 9, "docs/AGENT_CONSTITUTION.md: 14 rules, each with enforcing code, proving test, metric; coverage test (ccae579)"),
    (612, 9, "same contract, checked by tests/test_constitution.py"),
    (610, 9, "behavioural guidelines are the constitution's rules, enforced in code"),
    (611, 9, "rules of engagement = constitution + permission policy"),
    (616, 9, "behavioural guardrails measured per rule"),
    (622, 9, "agent behaviour policy written and enforced"),
    (648, 9, "discipline measured: scope, parsimony, test gaming, overreach"),
    (621, 8, "harness intent is written down as enforced rules"),
    (642, 8, "nudges correct scope, communication and test gaming once per run"),
    (637, 8, "coded failures + rule metrics close the loop"),
    # U24 architecture + parsimony (ceca98a)
    (674, 9, "trendlab arch: cycles, rule violations, oversized modules; new edges judged per run (ceca98a)"),
    (675, 8, "architecture rules enforced; design quality beyond imports is not"),
    (685, 8, "import graph + module size + fan-in report"),
    (686, 8, "parsimony measured per fix"),
    (687, 9, "parsimony: harness 94% of fixes within 2 lines of the minimal fix vs bare 80% (ceca98a)"),
    (632, 9, "same measurement"),
    (633, 9, "same measurement"),
    (634, 8, "minimal-fix share measured; terseness of prose handled by communication rules"),
    (579, 8, "new-definition budget + parsimony"),
    (580, 8, "same"),
    (848, 7, "plan lint + architecture rules before/after; no dedicated architecture step"),
    # U25 mutation testing (075a969)
    (149, 9, "trendlab mutate: survivors are untested behaviour; found the suite's boundary bugs (075a969)"),
    (567, 8, "mutation survivors point at missed edge cases"),
    (569, 8, "mutation testing surfaces latent bugs before they ship (075a969)"),
    (570, 8, "same"),
    (571, 6, "boundary mutants catch some paper-cut bugs; no broader check"),
    (566, 7, "weak/fabricated tests caught by test strength + mutation"),
    # U26 runtime controls (994b379)
    (47, 9, "one live run per checkout with stale-lock takeover; worktrees for parallel work (994b379)"),
    (38, 9, "[tools] allow/deny + --tools hide and refuse tools (994b379)"),
    (44, 9, "[limits] max_tokens_per_run with its own failure code (994b379)"),
    (538, 9, "edit → validation and edit → verdict seconds per bench row (994b379)"),
    (539, 8, "review is immediate (verifier/review gate); turnaround measured via verdict latency"),
    (540, 8, "prompt → first edit and edit → verdict measured"),
    (33, 8, "worktree runs, docker sandbox option, run lock"),
    (48, 8, "parallel read-only tool calls bounded by limits.parallel_tools"),
    (50, 8, "async tool execution and background processes"),
    # U27 security inventory (1c8339c)
    (456, 9, "trendlab surface: everything the agent can reach + risks (1c8339c)"),
    (457, 8, "trendlab audit against OSV; this repo 55 packages, 0 known vulnerabilities (1c8339c)"),
    (454, 8, "every capability listed with its policy; taints force approval"),
    (825, 8, "surface report + audit + local-first + no outward actions by default"),
]
