# Part I re-ratings. (term number, new rating, evidence). Evidence names a commit, a test file,
# or a measurement in docs/BENCH_LOG.md / the spec. Ratings stay put where the work is not done.
R = [
    (
        52,
        9,
        "git tools hidden outside repos, run_tests offered only with a test command (2b3e3ae, 777f673); live dashboard tool success rose once misrouted calls stopped",
    ),
    (53, 8, "selection is shaped by tool visibility rules and the route; no learned policy"),
    (
        55,
        9,
        "ask_json: JSON mode on OpenAI-compatible and Ollama, schema-checked parse with one repair round (777f673, tests)",
    ),
    (56, 9, "pydantic output models for verifier, router, judge, red-team via ask_json (777f673)"),
    (
        57,
        9,
        "every structured reply validated against its model; invalid → repair → explicit unusable (test_judge_quality)",
    ),
    (
        59,
        8,
        "runtime invariants + edit postconditions enforce contracts; tool schemas not versioned",
    ),
    (60, 8, "postconditions per edit tool (hash change, syntax parse) (93a1ae0)"),
    (61, 8, "read-before-edit precondition measured per run (read_before_edit metric)"),
    (
        62,
        9,
        "edit postconditions: file hash and syntax parse, TOOL_POSTCONDITION_FAILED event, tests (93a1ae0)",
    ),
    (
        63,
        9,
        "runtime invariants checked after every THINKING step, INVARIANT_VIOLATED event, tests (777f673)",
    ),
    (
        64,
        9,
        "same invariant checker; violations recorded on the run and in the bench row (777f673)",
    ),
    (
        74,
        9,
        "ToolHealth circuit breaker: opens after consecutive failures with a readable reason, TOOL_CIRCUIT_OPENED, test_tool_health (93a1ae0)",
    ),
    (
        76,
        9,
        "idempotent write/patch: unchanged content is a no-op, no FILE_CHANGED, no postcondition rerun (777f673, tests)",
    ),
    (
        79,
        9,
        "router picks a route and its settings (planner/verifier gating, safety floor); 95% rules / 98% model on a 40-prompt held-out set (2d7cd45)",
    ),
    (
        80,
        9,
        "Flash router model: 98% held-out accuracy, Brier 0.04, ~$0.0002 per call, never routes risky work below the floor (2d7cd45)",
    ),
    (81, 8, "intent classified by a model, not keywords; no embedding index by design"),
    (
        93,
        9,
        "spans, trace tree, OpenTelemetry export, session search, stats, retention, dashboard (8649a00, 2b3e3ae)",
    ),
    (95, 9, "trendlab trace renders the span tree per session; test_observability_depth (8649a00)"),
    (96, 9, "span id + parent id + duration on every event; SPAN_STARTED/ENDED (8649a00)"),
    (100, 9, "per-span durations, wall-time CI per task in bench (8649a00, 3a17e49)"),
    (
        102,
        9,
        "81-task suite across 6 tiers, SUITE_VERSION stamped, --verify-suite self-check (244b518)",
    ),
    (103, 9, "hidden tests + reference answers + holdout ids per task (380a06e, ddf4977)"),
    (107, 9, "hidden tests written outside the agent's view decide pass/fail"),
    (
        108,
        9,
        "hidden tests and reference content are the ground truth for verifier precision/recall",
    ),
    (109, 9, "reference_content per task; exact_match and ref_similarity per row (380a06e)"),
    (110, 9, "verifier rubric: correctness, minimality, safety, tests 0-2 (242a16c)"),
    (111, 9, "bench --scorecard (380a06e)"),
    (112, 9, "verifier scored against hidden tests: precision, recall, false-pass rate (380a06e)"),
    (
        113,
        9,
        "verifier + pairwise judge + second opinion, all measured against ground truth (242a16c)",
    ),
    (114, 9, "pairwise judge with position swap; inconsistent orders → tie (test_judge_quality)"),
    (115, 9, "pointwise verdict with rubric and confidence (242a16c)"),
    (116, 9, "rubric in the verifier schema, mean rubric in summaries (242a16c, 380a06e)"),
    (117, 9, "exact_match vs reference per row (380a06e)"),
    (118, 8, "ref_similarity (sequence ratio) per row; lexical, not semantic"),
    (121, 9, "pass rate with Wilson interval (3a17e49)"),
    (122, 9, "completion with interval and pass@k (3a17e49)"),
    (
        123,
        9,
        "per-tool success rate in every bench summary and in the dashboard (3a17e49, 93a1ae0)",
    ),
    (
        124,
        8,
        "unsupported-claims detector (negation-aware) gives a hallucination rate per row; not yet checked against human labels (380a06e, 004f295)",
    ),
    (125, 9, "error_rate in every summary (3a17e49)"),
    (126, 9, "classifier_metrics on verifier, router and injection scanner (380a06e)"),
    (127, 9, "same; scanner held-out recall 87%, router recall per route (004f295)"),
    (128, 9, "F1 reported with precision/recall (380a06e)"),
    (
        129,
        9,
        "false-pass and false-flag rates for the verifier; scanner FP 0.035% on real text (004f295)",
    ),
    (130, 9, "false-negative rate reported for scanner and verifier (380a06e)"),
    (131, 9, "ECE on verifier confidence and router (380a06e)"),
    (132, 9, "Brier score on verifier and router (router 0.04) (380a06e, 2d7cd45)"),
    (
        133,
        9,
        "[verification] min_confidence 0.5: low-confidence passes are not surfaced as passes (244b518)",
    ),
    (134, 9, "bench --gate: significance + cost-ratio thresholds (3a17e49)"),
    (
        136,
        9,
        "nightly canary with cause hints, history file, Telegram alert on drop (242a16c, 2b3e3ae)",
    ),
    (137, 9, "canary flags cost and wall-time regressions as well as pass drops (2b3e3ae)"),
    (138, 9, "canary pass-rate drop alert with interval (242a16c)"),
    (139, 8, "SUITE_VERSION stamped on rows; history comparable only within a version"),
    (
        140,
        8,
        "profile_sessions + total-variation distance over real sessions; drift --periods (2b3e3ae, 244b518)",
    ),
    (141, 9, "prompt_hash on every record; drift report flags changes (242a16c)"),
    (142, 9, "served model version stamped on every record and cost row (242a16c)"),
    (
        143,
        8,
        "shift report showed the suite did not match real work; realistic tier added to close it (2b3e3ae)",
    ),
    (144, 9, "adversarial tier ad01-ad05 live: harness 5/5 safe and fixed (cc36a93)"),
    (
        145,
        9,
        "red-team generator; agent resisted 15/15 generated attacks; scanner held-out recall 87% after 3 rounds (244b518, 004f295)",
    ),
    (146, 8, "bench --concurrency runs candidates in parallel; no sustained stress run recorded"),
    (147, 6, "concurrency flag only; no load profile"),
    (
        149,
        7,
        "generated-test strength check (fails when the fix is reverted) (c862202); no edge-case coverage metric",
    ),
    (
        150,
        9,
        "long tier lh01-lh04 live: bare 4/4, harness 4/4, harness read-before-edit 4/4 vs 3/4 (2026-10-08)",
    ),
    (151, 9, "multiturn tier mt01-mt04 live: both 4/4, follow-ups scripted per task (2026-10-08)"),
    (152, 9, "read_before_edit, validated_after_edit, tool success per row (cc36a93)"),
    (153, 8, "retrieval recall@3 81% offline (91% symptom-only) (e625908); live A/B in progress"),
    (154, 5, "plan_recall vs reference steps exists; planning package U7 not done"),
    (
        156,
        9,
        "safe + violations per row, forbid checks (exists/absent/unchanged/no_command) (cc36a93)",
    ),
    (158, 9, "--runs N, pass@k, flaky tasks list, interval (3a17e49)"),
    (159, 9, "wall-time per task with bootstrap interval (3a17e49)"),
    (160, 9, "cost per task with interval; cost ratio in the gate (3a17e49)"),
    (161, 8, "trendlab label: blind human labelling of runs (ddf4977)"),
    (162, 8, "label hides profile/model from the labeller (ddf4977)"),
    (163, 8, "Cohen's kappa between human labels and the verifier (ddf4977)"),
    (164, 9, "second-opinion verifier with agreement events (242a16c)"),
    (165, 8, "judge-bias probe: padded and restyled diffs must not flip verdicts (ddf4977)"),
    (166, 8, "same probe, reported per judge model"),
    (167, 9, "position swap on every pairwise call (test_judge_quality)"),
    (168, 8, "pad_diff probe measures verbosity bias (ddf4977)"),
    (169, 8, "restyle_diff probe measures style bias (ddf4977)"),
    (
        171,
        9,
        "leakage guard on every row: hidden-test text must not appear in the prompt (ddf4977)",
    ),
    (172, 9, "same guard; holdout ids never used for tuning (ddf4977)"),
    (
        173,
        6,
        "prompt-side leakage guarded; model training contamination cannot be checked from a harness",
    ),
    (
        174,
        9,
        "injection scanner on fetched/read content + taint gating that forces approval (cc36a93, 004f295)",
    ),
    (
        175,
        9,
        "indirect injection in files/tool output scanned; adversarial tier live 5/5 (cc36a93)",
    ),
    (176, 7, "red-team attacks resisted; no dedicated jailbreak corpus"),
    (178, 8, "test-tampering bait task ad04 + 'unchanged' forbid checks (cc36a93)"),
    (179, 8, "hidden tests the agent cannot see; scope checks catch gaming by deletion"),
    (180, 8, "agent cannot see or edit the grader; tampering bait measured"),
    (
        181,
        9,
        "holdout split; router overfit caught (100% suite vs 68% held-out) and corrected (2d7cd45)",
    ),
    (182, 9, "HOLDOUT_IDS + --holdout; router held-out set in tests/data (2d7cd45)"),
    (183, 9, "engine nightly canary (10 fixed tasks) at 03:30 (3a17e49, 242a16c)"),
    (185, 8, "online quality from live sessions: 94.7% validated-after-edit rate (244b518)"),
    (187, 9, "bench --compare with exact paired sign test and intervals (3a17e49)"),
    (188, 9, "gate compares challenger to champion on the same tasks (3a17e49)"),
    (189, 9, "nightly canary + history (3a17e49)"),
    (190, 9, "bench --gate exits non-zero on a significant drop or cost blow-out (3a17e49)"),
    (191, 9, "same gate used as the release check (3a17e49)"),
    (196, 8, "bench --counterfactual reruns failed tasks under another profile (244b518)"),
    (197, 9, "7 ablations + dotted overrides + --ablation (244b518)"),
    (198, 8, "bench --sweep over a config key (244b518)"),
    (199, 9, "Wilson and bootstrap intervals in every summary (3a17e49)"),
    (200, 9, "exact paired sign test in --compare (3a17e49)"),
]
