# Re-rating pass on remaining 7s/8s where measured evidence already exists, plus U31
# (feedback, SQL analytics, selftest). Model-capability terms wait for the model comparison.
R = [
    (568, 9, "off-by-one defects in the suite fixed live; mutation testing flags boundary flips (075a969)"),
    (557, 9, "overreach rate, scope budget, change scope and jailbreak tier all measured"),
    (599, 9, "destructive requests recoverable via checkpoints; jb04/ad05 held live"),
    (561, 8, "parsimony: 94% of harness fixes within 2 lines of minimal (ceca98a)"),
    (607, 9, "inbox cards by severity, FMEA ranking of failure modes, PR triage"),
    (608, 9, "verify → review → gate → canary → replay, each measured"),
    (641, 9, "nudges (scope, communication, latency), escalation, cooldown, co-design — each tested"),
    (738, 9, "review mode, router prompt and planner choice all adopted by measurement"),
    (760, 8, "tiered output, cache share, quick review; tokens per run tracked"),
    (774, 8, "fully loaded ledger of AI service use per project/role/model"),
    (777, 8, "cost per run and per validated change; per-prompt feedback"),
    (683, 8, "replay regression + canary protect existing behaviour"),
    (684, 8, "same, plus architecture rules and health trend"),
    (850, 8, "scope budget from the task and change scope before edits"),
    (441, 8, "remote approvals need HMAC decision tokens; Telegram checks chat id"),
    (444, 8, "per-request decision tokens; keys only in the secrets store"),
    (11, 9, "verifier round, confirmation pass, plan review, co-design; self-correction 98.9%"),
    (12, 9, "confirmation pass cut review noise from 1.16 to 0.16 per correct fix (f5e08f7)"),
    (53, 9, "routing, allowlist, availability rules and automatic fallback"),
    (59, 9, "constitution + postconditions + symbol and arch checks"),
    (60, 9, "tool schemas, postconditions, fallbacks, recorded results"),
    (61, 9, "read-before-edit, run lock, plan gate before first change"),
    (75, 9, "per-tool timeouts, wall-clock cap, latency budget, cooldown"),
    (86, 9, "layered context with measured compaction retention (0dc8673)"),
    (177, 9, "exfiltration taint, injection taint, allowlist, jailbreak tier"),
    (178, 9, "test-gaming detector + hidden tests + tampering bait (ccae579)"),
    (179, 9, "same"),
    (180, 9, "grader hidden from the agent; tampering detected"),
    (442, 9, "permission engine + HMAC approvals + plan gate"),
    (445, 9, "keys in a 0600 secrets store, never in config or output; exfil guard"),
    (537, 9, "pre-PR gate runs locally before CI"),
    (544, 9, "review structure lens + arch check of new import edges (ceca98a)"),
    (545, 9, "same"),
    (576, 9, "parsimony measured per fix (ceca98a)"),
    (577, 9, "health trend + parsimony"),
    (578, 9, "parsimony + new-definition budget"),
    (584, 9, "sycophancy tier live: 0/10 followed wrong diagnoses (ccae579)"),
    (597, 9, "overreach measured live: realistic questions answered with no edits"),
    (598, 9, "timidity measured live: no idle fixes in realistic or suite runs"),
    (643, 9, "both rates measured; route settings tune proactivity"),
    (680, 9, "replay regression + nightly canary + async review"),
    (697, 9, "served model and provider on every record; ledger per model"),
    (709, 9, "retention prunes sessions, events and cassettes together"),
    (718, 8, "`trendlab sql` read-only analytics over the store + JSONL/OTel export (538633f)"),
    (506, 8, "`trendlab feedback` per run; satisfaction in stats (538633f)"),
    (681, 9, "`trendlab selftest`: 8/8 end-to-end stages offline in ~9 s (538633f)"),
    (682, 9, "same self-test harness + 540 tests"),
    (802, 9, "failover, cooldown retries, run lock, deterministic replay"),
    (842, 9, "test-gaming, parsimony, symbol check, scope budget"),
    (843, 9, "health trend tracks accumulation"),
    (844, 9, "nudges + gates remove slop before it lands"),
    (856, 9, "verification gates surfacing; edit→verdict latency measured"),
    (857, 8, "quality and cost per validated change measured together"),
]
