# Re-ratings after U7 planning, U8 failure taxonomy, U9 governance, U10 economics, U11 security
# and the chaos / fault-tolerance fixes (2026-10-08).
R = [
    # U7 planning (e1009ce)
    (8, 9, "planner role + executor loop with per-step validation, dependency graph honoured, planner-only eval (e1009ce)"),
    (11, 8, "plan review → repair, verifier fix round, communication rewrite; no free-form self-reflection"),
    (12, 8, "deterministic plan critique (lint) and verifier critique; not model self-critique"),
    (14, 9, "planner splits work into 2-6 verifiable steps; live file recall 94-97% on 16 hard tasks (e1009ce)"),
    (15, 9, "plans generated with files, done_when, validation and dependencies; 100% valid live (e1009ce)"),
    (16, 9, "plan lint review with one repair call; divergence replanning (e1009ce, test_planning)"),
    (17, 9, "replans on a stalled step and when edits drift outside the plan, once per run (e1009ce)"),
    (18, 8, "goal → steps; no multi-level goal hierarchy"),
    (23, 9, "task graph: dependencies, ready set, waves, cycle detection; all live plans declared dependencies (e1009ce)"),
    (24, 8, "execution waves and parallel-safe groups computed and logged; steps still run in order"),
    (25, 9, "dependency graph enforced: a step cannot start before its prerequisites, failures block dependents (e1009ce)"),
    (154, 9, "bench --planning-eval: recall, precision, structure, lint; v4-pro vs Flash planner measured (e1009ce)"),
    (528, 9, "plan lint before any edit (invented files, missing validation, bad dependencies) + one repair (e1009ce)"),
    (531, 9, "decomposition → validated steps → dependency-ordered execution (e1009ce)"),
    (532, 8, "task text → steps with done_when conditions; no separate spec document step"),
    (849, 8, "plan reviewed before execution starts"),
    # U8 failure taxonomy (0501a38)
    (192, 9, "one taxonomy (21 codes) on runs, bench rows and meta cards; real store 411 runs, 0 unclassified (0501a38)"),
    (193, 9, "runtime stop reasons, provider errors and hidden-test outcomes map to codes; coverage test (0501a38)"),
    (194, 9, "trendlab rca: first warning sign, signal chain, causes, remedies, suspect files per run (0501a38)"),
    (195, 9, "FMEA: severity x occurrence x detection ranking in trendlab failures (0501a38)"),
    # chaos / fault tolerance (1dffa3f)
    (148, 9, "live canary at 20% injected provider faults: 18 injected, 10/10 completed and passed; wiring bug found and fixed (1dffa3f)"),
    (68, 9, "gateway retries + run-level cooldown retries; chaos canary 10/10 (1dffa3f)"),
    (66, 9, "recovery events for every failure class incl. cooldown retry; bounded (1dffa3f)"),
    (157, 9, "typos 10/10, 20% chaos 10/10, adversarial 5/5 safe, multi-turn and long 4/4 live (2026-10-08)"),
    (803, 8, "provider outages absorbed by retries and cooldowns; no offline mode"),
    (804, 9, "transient outages survived at run level, measured under injected faults (1dffa3f)"),
    (805, 9, "same, plus engine keeps running when one job fails"),
    # U9 governance (8c331e8)
    (627, 9, "[governance] change_allow / --allow-path: edits outside the globs refused, tested (8c331e8)"),
    (645, 9, "change scope enforced at the mutation hook + scope budget nudge (8c331e8, c862202)"),
    (628, 9, "max_answer_words stated in the system prompt, checked, one rewrite (8c331e8)"),
    (629, 7, "tone stated in the system prompt; filler phrases checked, tone itself not scored"),
    (630, 9, "plain-language rules: sentence length, acronyms, walls of text, checked on every answer (8c331e8)"),
    (631, 6, "sentence-length and acronym rules approximate it; no controlled vocabulary"),
    (585, 9, "filler-phrase detection on every answer; real answers: 0% (8c331e8)"),
    (586, 7, "undefined acronyms flagged; no jargon dictionary"),
    (587, 8, "undefined-acronym check, ~94% precision on 364 real answers (8c331e8)"),
    (588, 9, "walls of text detected and rewritten when plain language is on (8c331e8)"),
    (589, 8, "answer style per period in stats (median words, reading ease, filler rate)"),
    (617, 8, "communication rules injected as a structured system-prompt block"),
    (635, 8, "configurable answer rules + final report format"),
    (507, 9, "commit_per_turn: one commit per turn on trendlab/turns/<session>, HEAD and index untouched (8c331e8)"),
    (508, 9, "turn branch is a single-turn commit history with prompt, status, files, validation (8c331e8)"),
    (509, 9, "trendlab turns [--patch] reviews each turn's diff (8c331e8)"),
    (541, 8, "review per turn or per run; no per-hunk review"),
    (556, 9, "change scope refusal + permission engine + checkpoints (8c331e8)"),
    # U10 economics (3614a6b)
    (754, 9, "trendlab cost: spend per project with runs, validated changes and ROI (3614a6b)"),
    (765, 9, "every role persisted (planner/verifier/router spend was being lost); overhead share per project (3614a6b)"),
    (776, 9, "validated changes per dollar per project; bench passes per dollar (3614a6b)"),
    (777, 7, "cost per run and per validated change; no per-prompt listing"),
    (778, 8, "spend on sessions that never completed reported as waste"),
    (779, 9, "comparisons report USD per extra pass and per extra tested pass; planner Pro vs Flash measured (3614a6b, e1009ce)"),
    (749, 8, "cache share of input tokens per project"),
    (759, 8, "cache share, tokens and cost by role and model per project"),
    (761, 8, "overhead and waste shares make inefficiency visible per project"),
    (766, 8, "cost per validated change, overhead and cache economics per project"),
    (771, 8, "spend split into project work vs benchmarks vs scratch: 93% of 60-day spend was evaluation (3614a6b)"),
    (772, 7, "project buckets only; no business tags"),
    (773, 8, "ledger attributes every dollar to a project, role and model"),
    (775, 9, "ledger + stats + period-over-period change (3614a6b)"),
    (783, 8, "Pro planner measured at 3.5x Flash cost with no better plans (e1009ce)"),
    (790, 9, "monthly and per-project budgets; engine alerts once per threshold per month (3614a6b)"),
    (791, 9, "same: inbox card + Telegram at each threshold (3614a6b)"),
    (792, 9, "configurable alert_at thresholds (3614a6b)"),
    (793, 9, "budgets, alerts, ledger and fully loaded cost together (3614a6b)"),
    # U11 security (7d75215)
    (455, 8, "threat categories: injection, jailbreak, exfiltration, destructive, outside-project"),
    (456, 7, "network-after-secret path closed; shell remains the broad surface"),
    (177, 8, "network calls after a secret read need approval in every mode (7d75215)"),
    (454, 7, "secret taint and injection taint force approval regardless of mode"),
]
